version: '3'
services:
  bot:
    depends_on:
      - black
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

  black:
    container_name: black
    build:
      dockerfile: black.Dockerfile
    ports:
      - "9090:9090"
